- name: Configure rsyslog and command logging
  hosts: all
  become: yes
  vars:
    corelog_ip: "192.168.1.100"  # Set your Corelog server IP
    rsyslog_conf: "/etc/rsyslog.conf"

  tasks:
    - name: Add required template and forwarding rule
      ansible.builtin.blockinfile:
        path: "{{ rsyslog_conf }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - REMOTE LOGGING"
        block: |
          $template noTimestampFormat,"%syslogtag%%msg%\\n"
          kern.*;user.*;daemon.*;auth.*;authpriv.*;syslog.*;cron.*;security.* @{{ corelog_ip }}:514;noTimestampFormat
        insertafter: EOF
      notify: restart rsyslog

  handlers:
    - name: restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted
